export const languages = [
  {
    language: "Spanish",
    "encrypt-area": "Ingrese el texto aquí",
    "info": "Solo letras minúsculas y sin acentos",
    "btn-encrypt": "Encriptar",
    "btn-desencrypt": "Desencriptar",
    "desencrypt_h2--visible": "Ningún mensaje fue encontrado",
    "desencrypt_p--visible":
      "Ingresa el texto que desees encriptar o desencriptar",
    "copy-text": "Copiar",
    "option-language": "Selecciona un idioma",
  },
  {
    language: "Portuguese",
    "encrypt-area": "Digite o texto aqui",
    "info": "Somente letras minúsculas sem acentos",
    "btn-encrypt": "Criptografar",
    "btn-desencrypt": "Descriptografar",
    "desencrypt_h2--visible": "Nenhuma mensagem encontrada",
    "desencrypt_p--visible":
      "Digite o texto que deseja criptografar ou descriptografar",
    "copy-text": "Copiar",
    "option-language": "Selecione um idioma",
  },
  {
    language: "English",
    "encrypt-area": "Enter text here",
    "info": "Only lowercase letters without accents",
    "btn-encrypt": "Encrypt",
    "btn-desencrypt": "Decrypt",
    "desencrypt_h2--visible": "No message found",
    "desencrypt_p--visible": "Enter the text you want to encrypt or decrypt",
    "copy-text": "Copy",
    "option-language": "Select a language",
  },
  {
    language: "French",
    "encrypt-area": "Entrez le texte ici",
    "info": "Seulement des lettres minuscules sans accents",
    "btn-encrypt": "Chiffrer",
    "btn-desencrypt": "Déchiffrer",
    "desencrypt_h2--visible": "Aucun message trouvé",
    "desencrypt_p--visible":
      "Entrez le texte que vous souhaitez chiffrer ou déchiffrer",
    "copy-text": "Copier",
    "option-language": "Sélectionnez une langue",
  },
  {
    language: "German",
    "encrypt-area": "Geben Sie hier den Text ein",
    "info": "Nur Kleinbuchstaben ohne Akzente",
    "btn-encrypt": "Verschlüsseln",
    "btn-desencrypt": "Entschlüsseln",
    "desencrypt_h2--visible": "Keine Nachricht gefunden",
    "desencrypt_p--visible":
      "Geben Sie den Text ein, den Sie verschlüsseln oder entschlüsseln möchten",
    "copy-text": "Kopieren",
    "option-language": "Wählen Sie eine Sprache aus",
  },
  {
    language: "Italian",
    "encrypt-area": "Inserisci il testo qui",
    "info": "Solo lettere minuscole senza accenti",
    "btn-encrypt": "Criptare",
    "btn-desencrypt": "Decrittare",
    "desencrypt_h2--visible": "Nessun messaggio trovato",
    "desencrypt_p--visible":
      "Inserisci il testo che desideri criptare o decrittare",
    "copy-text": "Copia",
    "option-language": "Seleziona una lingua",
  },
  {
    language: "Japanese",
    "encrypt-area": "ここにテキストを入力してください",
    "info": "アクセントのない小文字のみ",
    "btn-encrypt": "暗号化する",
    "btn-desencrypt": "復号化する",
    "desencrypt_h2--visible": "メッセージが見つかりませんでした",
    "desencrypt_p--visible": "暗号化または復号化するテキストを入力してください",
    "copy-text": "コピー",
    "option-language": "言語を選択",
  },
  {
    language: "Korean",
    "encrypt-area": "여기에 텍스트를 입력하세요",
    "info": "강세 없는 소문자 만",
    "btn-encrypt": "암호화",
    "btn-desencrypt": "복호화",
    "desencrypt_h2--visible": "메시지를 찾을 수 없습니다",
    "desencrypt_p--visible": "암호화 또는 복호화 할 텍스트를 입력하세요",
    "copy-text": "복사",
    "option-language": "언어 선택",
  },
  {
    language: "Russian",
    "encrypt-area": "Введите текст здесь",
    "info": "Только строчные буквы без ударений",
    "btn-encrypt": "Зашифровать",
    "btn-desencrypt": "Расшифровать",
    "desencrypt_h2--visible": "Сообщение не найдено",
    "desencrypt_p--visible":
      "Введите текст, который вы хотите зашифровать или расшифровать",
    "copy-text": "Копировать",
    "option-language": "Выберите язык",
  },
  {
    language: "Arabic",
    "encrypt-area": "أدخل النص هنا",
    "info": "فقط الأحرف الصغيرة بدون حروف ملونة",
    "btn-encrypt": "تشفير",
    "btn-desencrypt": "فك التشفير",
    "desencrypt_h2--visible": "لم يتم العثور على رسالة",
    "desencrypt_p--visible": "أدخل النص الذي تريد تشفيره أو فك تشفيره",
    "copy-text": "نسخ",
    "option-language": "اختر لغة",
  },
  {
    language: "Chinese",
    "encrypt-area": "在此处输入文本",
    "info": "仅小写字母没有重音符号",
    "btn-encrypt": "加密",
    "btn-desencrypt": "解密",
    "desencrypt_h2--visible": "未找到消息",
    "desencrypt_p--visible": "输入您想要加密或解密的文本",
    "copy-text": "复制",
    "option-language": "选择一种语言"
  },
]
